import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Frequently Asked Questions",
    description: "Find answers to common questions about BandhanNova accounts, AI services, privacy, and more.",
    alternates: { canonical: "https://policies.bandhannova.in/faq" },
};

const faqs = [
    {
        category: "Account & Access",
        icon: "👤",
        questions: [
            {
                q: "What is a BandhanNova Account?",
                a: "A BandhanNova Account is your single login for every BandhanNova product — AI Hub, Chat, Blogs, Academy, Smartpedia, Bani AI, and more. One account gives you access to the entire ecosystem.",
            },
            {
                q: "How do I create a BandhanNova Account?",
                a: "Visit accounts.bandhannova.in/signup and sign up with your email or Google account. It's free and takes less than a minute.",
            },
            {
                q: "Can I sign in with Google?",
                a: "Yes! We support Google Sign-In for a quick and secure authentication experience. Just click \"Continue with Google\" on the sign-in page.",
            },
            {
                q: "How do I reset my password?",
                a: "Go to the sign-in page and click \"Forgot password?\" — we'll send a reset link to your registered email address.",
            },
            {
                q: "Can I delete my account?",
                a: "Yes. You can request account deletion by contacting us at support@bandhannova.in. Your data will be removed within 30 days.",
            },
        ],
    },
    {
        category: "AI Services",
        icon: "🧠",
        questions: [
            {
                q: "What AI models does BandhanNova use?",
                a: "BandhanNova AI Hub uses state-of-the-art language models for different tasks — conversational AI, code generation, creative writing, research, and more. We continuously upgrade our models for better quality.",
            },
            {
                q: "Are my AI conversations private?",
                a: "Absolutely. Your conversations are stored securely and are never shared with third parties, advertisers, or other users. See our Privacy Policy for details.",
            },
            {
                q: "Can I use AI-generated content commercially?",
                a: "Yes, you can use the content generated by our AI for personal or commercial purposes. However, always verify AI outputs before relying on them for important decisions.",
            },
            {
                q: "How many free queries do guests get?",
                a: "Guest users get 5 free queries. After that, you'll need to create a free account for unlimited access to our AI services.",
            },
            {
                q: "Does BandhanNova AI make mistakes?",
                a: "Yes — like all AI systems, BandhanNova AI can make mistakes. We recommend double-checking important information independently, especially for medical, legal, or financial advice.",
            },
        ],
    },
    {
        category: "Privacy & Security",
        icon: "🔒",
        questions: [
            {
                q: "Does BandhanNova sell my data?",
                a: "Never. We do not and will never sell your personal information to third parties. Your data is used solely to provide and improve our services.",
            },
            {
                q: "How is my data protected?",
                a: "We use industry-standard encryption (TLS/SSL), secure authentication via Supabase with row-level security, and strict access controls. Your data is encrypted both in transit and at rest.",
            },
            {
                q: "What data does BandhanNova collect?",
                a: "We collect account data (name, email), usage data (features used), device information, and content you create. See our Privacy Policy for the full breakdown.",
            },
            {
                q: "Can I download my data?",
                a: "Yes. You can request a copy of your personal data by contacting support@bandhannova.in. We'll provide it in a portable format within a reasonable timeframe.",
            },
        ],
    },
    {
        category: "Products & Services",
        icon: "🚀",
        questions: [
            {
                q: "What products are part of BandhanNova?",
                a: "BandhanNova includes AI Hub (AI chat), Chat (messaging), Blogs (publishing), Academy (learning), Smartpedia (search), Bani AI (personal assistant), BSCCA (cricket), and more — all accessible with one account.",
            },
            {
                q: "Is BandhanNova free?",
                a: "Yes! BandhanNova Accounts and core features are completely free. Some premium features may have usage limits or subscription options in the future.",
            },
            {
                q: "Which devices are supported?",
                a: "BandhanNova works on any modern web browser — Chrome, Firefox, Safari, Edge — across desktop, mobile, and tablet devices.",
            },
            {
                q: "Is BandhanNova available offline?",
                a: "Some features may work offline if you've installed the app as a PWA (Progressive Web App). However, AI features require an internet connection.",
            },
        ],
    },
    {
        category: "Support",
        icon: "💬",
        questions: [
            {
                q: "How do I contact BandhanNova support?",
                a: "Email us at support@bandhannova.in — we typically respond within 24-48 hours.",
            },
            {
                q: "Where can I report a bug?",
                a: "Please report bugs by emailing support@bandhannova.in with a description of the issue, your device/browser information, and screenshots if possible.",
            },
            {
                q: "Can I suggest a new feature?",
                a: "We'd love to hear your ideas! Send feature requests to support@bandhannova.in and we'll consider them for future updates.",
            },
        ],
    },
];

export default function FAQPage() {
    return (
        <div className="policy-container">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "FAQPage",
                        "mainEntity": faqs.flatMap(section =>
                            section.questions.map(item => ({
                                "@type": "Question",
                                "name": item.q,
                                "acceptedAnswer": {
                                    "@type": "Answer",
                                    "text": item.a
                                }
                            }))
                        )
                    })
                }}
            />
            {/* Header */}
            <div className="animate-in">
                <div className="policy-badge" style={{ background: "#fef3c7", color: "#d97706" }}>
                    ❓ FAQs
                </div>
                <h1 className="policy-title">Frequently Asked Questions</h1>
                <p className="policy-subtitle">
                    Quick answers to common questions about BandhanNova, your account, privacy, and our services.
                </p>
            </div>

            {/* FAQ Sections */}
            {faqs.map((section, sectionIdx) => (
                <div key={section.category} className="animate-in-delay-1" style={{ marginBottom: "48px" }}>
                    {/* Category Header */}
                    <div
                        style={{
                            display: "flex",
                            alignItems: "center",
                            gap: "10px",
                            marginBottom: "20px",
                            paddingBottom: "12px",
                            borderBottom: "1px solid var(--border-light)",
                        }}
                    >
                        <span style={{ fontSize: "1.5rem" }}>{section.icon}</span>
                        <h2
                            style={{
                                fontSize: "1.25rem",
                                fontWeight: 700,
                                color: "var(--text-primary)",
                                letterSpacing: "-0.01em",
                            }}
                        >
                            {section.category}
                        </h2>
                    </div>

                    {/* Questions */}
                    <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                        {section.questions.map((item, qIdx) => (
                            <details
                                key={qIdx}
                                className="faq-item"
                                style={{
                                    background: "var(--bg-card)",
                                    border: "1px solid var(--border)",
                                    borderRadius: "14px",
                                    overflow: "hidden",
                                    transition: "all 0.2s ease",
                                }}
                            >
                                <summary
                                    style={{
                                        padding: "18px 22px",
                                        fontSize: "0.9375rem",
                                        fontWeight: 600,
                                        color: "var(--text-primary)",
                                        cursor: "pointer",
                                        listStyle: "none",
                                        display: "flex",
                                        alignItems: "center",
                                        justifyContent: "space-between",
                                        gap: "12px",
                                        userSelect: "none",
                                        lineHeight: 1.5,
                                    }}
                                >
                                    <span>{item.q}</span>
                                    <span
                                        style={{
                                            fontSize: "1.25rem",
                                            color: "var(--text-tertiary)",
                                            transition: "transform 0.2s",
                                            flexShrink: 0,
                                        }}
                                        className="faq-chevron"
                                    >
                                        +
                                    </span>
                                </summary>
                                <div
                                    style={{
                                        padding: "0 22px 18px",
                                        fontSize: "0.875rem",
                                        color: "var(--text-secondary)",
                                        lineHeight: 1.8,
                                        borderTop: "1px solid var(--border-light)",
                                        paddingTop: "14px",
                                        marginTop: "-2px",
                                    }}
                                >
                                    {item.a}
                                </div>
                            </details>
                        ))}
                    </div>
                </div>
            ))}

            {/* Still have questions */}
            <div
                className="info-card"
                style={{
                    textAlign: "center",
                    background: "#fef3c7",
                    borderColor: "rgba(217, 119, 6, 0.1)",
                    marginTop: "16px",
                }}
            >
                <strong style={{ color: "#d97706" }}>Still have questions?</strong>
                <p style={{ color: "#92400e" }}>
                    Reach out to us at{" "}
                    <a href="mailto:support@bandhannova.in" style={{ color: "#d97706", fontWeight: 600 }}>
                        support@bandhannova.in
                    </a>{" "}
                    — we{"\u2019"}re happy to help!
                </p>
            </div>
        </div>
    );
}
